/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DecoupledGUI.java
 *
 * Created on Dec 7, 2011, 2:02:37 PM
 */
package negotiator.gui;

/**
 *
 * @author Mark
 */
public class DecoupledGUI extends javax.swing.JFrame {

    /** Creates new form DecoupledGUI */
    public DecoupledGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        omLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        osList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        asList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        omParams = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        asParams = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        osParams = new javax.swing.JList();
        asLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        omList = new javax.swing.JList();
        osLabel = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Decoupled agents");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 170, 20));

        omLabel.setText("Opponent Model");
        omLabel.setName("omLabel"); // NOI18N
        getContentPane().add(omLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 170, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        osList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        osList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        osList.setName("osList"); // NOI18N
        jScrollPane2.setViewportView(osList);
        osList.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 204));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        asList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        asList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        asList.setName("asList"); // NOI18N
        jScrollPane3.setViewportView(asList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 40, 190, 204));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        omParams.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        omParams.setName("omVars"); // NOI18N
        jScrollPane1.setViewportView(omParams);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 170, 83));

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList5.setName("jList5"); // NOI18N
        jScrollPane6.setViewportView(jList5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 253, 170, 0));

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        asParams.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        asParams.setName("asVars"); // NOI18N
        jScrollPane8.setViewportView(asParams);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 260, 190, 83));

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList4.setName("jList4"); // NOI18N
        jScrollPane4.setViewportView(jList4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 590, 180));

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        osParams.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        osParams.setName("osVars"); // NOI18N
        jScrollPane5.setViewportView(osParams);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 260, 170, 83));

        asLabel.setText("Acceptance Strategy");
        asLabel.setName("asLabel"); // NOI18N
        getContentPane().add(asLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 13, 122, -1));

        jButton1.setText("Add variable");
        jButton1.setName("jButton1"); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, -1));

        jButton3.setText("Add variable");
        jButton3.setName("jButton3"); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 120, -1));

        jButton5.setText("Add decoupled agents");
        jButton5.setName("jButton5"); // NOI18N
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 170, 30));

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        jList8.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList8.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList8.setName("jList8"); // NOI18N
        jScrollPane7.setViewportView(jList8);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 40, 190, 204));

        jSeparator1.setName("jSeparator1"); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 620, -1));

        jScrollPane9.setName("jScrollPane9"); // NOI18N

        omList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        omList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        omList.setName("omList"); // NOI18N
        jScrollPane9.setViewportView(omList);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 180, 204));

        osLabel.setText("Offering Strategy");
        osLabel.setName("osLabel"); // NOI18N
        getContentPane().add(osLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 170, -1));

        jButton8.setText("Add variable");
        jButton8.setName("jButton8"); // NOI18N
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecoupledGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecoupledGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecoupledGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecoupledGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DecoupledGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asLabel;
    private javax.swing.JList asList;
    private javax.swing.JList asParams;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel omLabel;
    private javax.swing.JList omList;
    private javax.swing.JList omParams;
    private javax.swing.JLabel osLabel;
    private javax.swing.JList osList;
    private javax.swing.JList osParams;
    // End of variables declaration//GEN-END:variables
}
